#MRNA van de Bos Taurus
mrna_bos_taurus = """GGGGGGACTTAGCTCCAAAGCTGGCGCTTGGAAGTTAGGGACAGCGTCGCCGACTTGGTAGCCGCCGCAG
CATTCGCCGCGGATAAAGCCGGGGTCTACCATACCCACTGATTAACTATGGAAGACTATACCAAAATAGA
GAAAATTGGAGAAGGTACCTATGGAGTTGTGTATAAGGGTAGACACAAAACTACAGGCCAAGTGGTAGCC
ATGAAGAAAATCAGACTAGAAAGTGAAGAGGAAGGGGTTCCTAGTACTGCAATTCGGGAAATATCTCTAT
TAAAAGAGCTTCGTCATCCAAATATAGTCAGTCTTCAAGATGTGCTTATGCAGGATTCCAGGTTGTATCT
CATCTTTGAATTCCTTTCCATGGATCTCAAGAAATACTTGGATTCTATCCCTCCTGGTCAGTTCATGGAT
TCTTCACTTGTTAAGAGTTATTTGTACCAAATCCTACAAGGGATTGTGTTTTGTCACTCTAGAAGAGTTC
TCCACAGGGACTTAAAACCTCAAAATCTATTGATTGATGATAAAGGAACAATTAAGTTGGCAGATTTTGG
CCTTGCCAGAGCTTTTGGAATTCCTATTAGAGTATATACACATGAGGTAGTGACACTCTGGTATAGATCT
CCAGAAGTATTGCTGGGGTCAGCTGGCTACTCAACTCCAGTGGACATTTGGAGTATAGGTACCATATTTG
CTGAATTAGCAACGAAGAAACCACTTTTTCATGGGGATTCAGAAATTGATCAACTCTTCAGAATTTTCAG
AGCTTTGGGCACTCCCAATAATGAAGTGTGGCCAGAAGTGGAATCTTTACAGGACTATAAGAGTACATTT
CCCAAGTGGAAACCAGGAAGCTTAGCATCCCATGTCAAAAACTTGGATGAAAATGGCTTGGATCTGCTCT
CGAAAATGTTAATCTATGATCCTGCCAAACGAATTTCTGGCAAAATGGCACTGAATCATCCGTACTTTAA
TGATTTGGACAGTCAAATTAAGAAGATGTAGCTTTCTGACAGTTTCCCTGTGTTGTGTCAAGAGCAGATA
ATTGTACTTTTACTGTTCATCTCTGGTTTTGTCTTGTATATTTTTCTTTTCTTTGTTGTAAAACTTAATC
TGTACTTCATCTTCTGATTTCAAAACTAAGTTAAAATGTAAATACTGTTCTATATGAATTTAAATATAAT
AATTCTGTATATGTTTGTAGATTCCACTGTAACAGCTGTTTGTTACTATAATAAAACTTTATAAATCT"""

#Lengte berekenen zonder enters
lengte_mrna_bos_taurus = len(mrna_bos_taurus.replace("\n",""))
print ("Lengte mRNA van de Bos Taurus:", (lengte_mrna_bos_taurus))

#Aantal ATCG
aantal_a = mrna_bos_taurus.count("A")
aantal_t = mrna_bos_taurus.count("T")
aantal_c = mrna_bos_taurus.count("C")
aantal_g = mrna_bos_taurus.count("G")

print ("Aantal A:", aantal_a)
print ("Aantal T:", aantal_t)
print ("Aantal C:", aantal_c)
print ("Aantal G:", aantal_g)

#GC%
aantal_gc = aantal_c+aantal_g
gc_percentage = aantal_gc / lengte_mrna_bos_taurus * 100
print ("Het GC% van het mRNA van de Bos Taurus is:", gc_percentage, "%")






